"use strict";

function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } }

function _asyncToGenerator(fn) { return function () { var self = this, args = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(self, args); function _next(value) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value); } function _throw(err) { asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err); } _next(undefined); }); }; }

// Keeping this file for reference We wont actually use it
var express = require('express');

var router = express.Router();

var auth = require('../middleware/auth');

var jwt = require('jsonwebtoken');

var _require = require('express-validator'),
    check = _require.check,
    validationResult = _require.validationResult;

var bcrypt = require('bcrypt');

require("regenerator-runtime/runtime");

var User = require('../../models/userModel'); // req: application/json
// res: json || error code


router.get('/', auth,
/*#__PURE__*/
function () {
  var _ref = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee(req, res) {
    var user;
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.prev = 0;
            _context.next = 3;
            return User.findById(req.user.id).select('-password');

          case 3:
            user = _context.sent;
            res.json(user);
            _context.next = 11;
            break;

          case 7:
            _context.prev = 7;
            _context.t0 = _context["catch"](0);
            console.error(_context.t0.message);
            res.status(500).json({
              msg: 'Server Error'
            });

          case 11:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, null, [[0, 7]]);
  }));

  return function (_x, _x2) {
    return _ref.apply(this, arguments);
  };
}()); // @TYPE POST
// @DESC Login - Authenticate user & get token
// Public

router.post('/', [check('userName', 'Please enter a username with 3 or more characters').isLength(3), check('password', 'Password is required').exists()],
/*#__PURE__*/
// req: application/json
// res: json || error code
function () {
  var _ref2 = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee2(req, res) {
    var errors, _req$body, userName, password, user, isMatch, payload;

    return regeneratorRuntime.wrap(function _callee2$(_context2) {
      while (1) {
        switch (_context2.prev = _context2.next) {
          case 0:
            // Makes sure the signup is valid
            errors = validationResult(req);

            if (errors.isEmpty()) {
              _context2.next = 3;
              break;
            }

            return _context2.abrupt("return", res.status(400).json({
              errors: errors.array()
            }));

          case 3:
            // Assigns request body to user schema fields
            _req$body = req.body, userName = _req$body.userName, password = _req$body.password;
            _context2.prev = 4;
            _context2.next = 7;
            return User.findOne({
              userName: userName
            });

          case 7:
            user = _context2.sent;

            if (!(user == null)) {
              _context2.next = 10;
              break;
            }

            return _context2.abrupt("return", res.status(400).json({
              errors: [{
                msg: 'Invalid Credentials'
              }]
            }));

          case 10:
            _context2.next = 12;
            return bcrypt.compare(password, user.password);

          case 12:
            isMatch = _context2.sent;

            if (isMatch) {
              _context2.next = 15;
              break;
            }

            return _context2.abrupt("return", res.status(400).json({
              errors: [{
                msg: 'Invalid Credentials'
              }]
            }));

          case 15:
            payload = {
              user: {
                // Primary key id generated by Mongo
                id: user.id
              }
            }; // expiresIn 4 hour 

            jwt.sign(payload, process.env.SECRET, {
              expiresIn: 14400
            }, function (err, token) {
              if (err) throw err;
              res.json({
                token: token
              });
            });
            _context2.next = 23;
            break;

          case 19:
            _context2.prev = 19;
            _context2.t0 = _context2["catch"](4);
            console.error(_context2.t0.message);
            res.status(500).json({
              msg: 'Server error'
            });

          case 23:
          case "end":
            return _context2.stop();
        }
      }
    }, _callee2, null, [[4, 19]]);
  }));

  return function (_x3, _x4) {
    return _ref2.apply(this, arguments);
  };
}());
module.exports = router;