version: '3'

services:
  test:
    container_name: fortuna-test
    build:
      context: ./frontend_fortuna_v2/
      dockerfile: test.Dockerfile
    volumes:
      - "nodemodules:/app/node_modules"
      - "./frontend_fortuna_v2:/app"
    command: npm test

volumes:
  nodemodules: