FROM node:12.2.0-alpine AS builder

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm i --silent

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run deploy


### copy into caddy stage

FROM caddy:2.1.1-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443